nelmio_api_doc:
    documentation:
        info:
            title: Rotterdammerk
            description: OpenAPI file for Rotterdammerk
            version: 1.0.0
    areas: # to filter documented areas
        default: 
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        admin:
            path_patterns:
                - ^/admin # Accepts routes under /admin
        shop:
            path_patterns:
                - ^/shop # Accepts routes under /shop