CREATE DATABASE IF NOT EXISTS rotterdammerk;
CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app';
GRANT ALL PRIVILEGES ON rotterdammerk.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON `app`.* TO 'app'@'%';
FLUSH PRIVILEGES;
